# HLint configuration file
# https://github.com/ndmitchell/hlint

- group: {name: generalise, enabled: true}

# Ignoring certain hints in test-suites
# These hints are inapplicable since the test-suites are testing the properties
# that the hint assumes to be true.

- ignore: {name: "Functor law", within: ["Control.Evaluation.Test"] }

- ignore: {name: Use >=>, within: [Control.Evaluation.Test] }




