os:       linux
dist:     bionic
language: haskell
cabal:   "3.0"


addons:
  apt:
    sources:
    - hvr-ghc
    - ubuntu-toolchain-r-test
    packages:
    - gcc-9
    - g++-9


cache:
  directories:
    - "$HOME/.cabal/store"
    - "$HOME/.stack"
    - "$TRAVIS_BUILD_DIR/.stack-work"


jobs:
  include:
    - ghc: 8.8.3
    - ghc: 8.10.1


before_install:
  # Install newest version of GCC we can get. GHC-8.10.1 messes up with old GCC versions.
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9

  # Ensure that this directory exists for tool installs
  - mkdir -p /home/travis/.local/bin

  # Download and unpack the hlint executable
  - travis_retry curl --progress-bar --location -ohlint.tar.gz https://github.com/$(curl --silent https://github.com/ndmitchell/hlint/releases | grep -o '\"[^\"]*-x86_64-'$TRAVIS_OS_NAME'\.tar\.gz\"' | sed s/\"//g | head -n1)
  - tar -xzf hlint.tar.gz
  - cp -r hlint-*/data  ~/.local/bin/data
  - cp    hlint-*/hlint ~/.local/bin/hlint

  # Download and unpack the weeder executable
#  - which weeder || travis_retry curl --progress-bar --location -oweeder.tar.gz https://github.com/$(curl --silent https://github.com/ndmitchell/weeder/releases | grep -o '\"[^\"]*-x86_64-'$TRAVIS_OS_NAME'\.tar\.gz\"' | sed s/\"//g | head -n1)
#  - which weeder || tar -xzf weeder.tar.gz
#  - which weeder || cp weeder-*/weeder ~/.local/bin/weeder


install:
  - gcc    --version
  - g++    --version
  - ghc    --version
  - hlint  --version
# - weeder --version
  - cabal  --version
  - cabal update
  - cabal configure --with-compiler=ghc
  - cabal build --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal


script:
  - make run-hlint


git:
  depth: 5


notifications:
  email: false
