- package:
  - name: pcg-file-parsers
  - section:
    - name: exe:file-tests test:unit-tests
    - message:
      - name: Module reused between components
      - module: Test.Custom.Parse
  - section:
    - name: library test:unit-tests
    - message:
      - name: Module reused between components
      - module:
        - File.Format.Fasta.Internal
        - File.Format.Fasta.Parser
        - File.Format.Fastc.Parser
        - File.Format.Newick.Internal
        - File.Format.Newick.Parser
        - File.Format.TNT.Command.CCode
        - File.Format.TNT.Command.CNames
        - File.Format.TNT.Command.Procedure
        - File.Format.TNT.Command.TRead
        - File.Format.TNT.Command.XRead
        - File.Format.TNT.Internal
        - File.Format.TransitionCostMatrix.Parser
        - File.Format.VertexEdgeRoot.Parser
        - Text.Megaparsec.Custom
- package:
  - name: phylocomgraph
  - section:
    - name: library
    - message:
      - name: Weeds exported
      - module:
        - name: Bio.Metadata.Dynamic.Class
        - identifier: threewayTransitionCostMatrix
  - section:
    - name: library test:unit-tests
    - message:
      - name: Module reused between components
      - module:
        - Analysis.Parsimony.Dynamic.DirectOptimization.Pairwise.FFI
        - Analysis.Parsimony.Dynamic.DirectOptimization.Pairwise.Internal
        - Analysis.Parsimony.Dynamic.DirectOptimization.Pairwise.NeedlemanWunsch
        - Analysis.Parsimony.Dynamic.DirectOptimization.Pairwise.Ukkonen
        - Analysis.Parsimony.Dynamic.DirectOptimization.Pairwise.Ukkonen.Internal
        - Analysis.Parsimony.Dynamic.DirectOptimization.Pairwise.Ukkonen.Ribbon
        - Analysis.Parsimony.Internal
        - Bio.Character
        - Bio.Character.Encodable
        - Bio.Character.Encodable.Continuous
        - Bio.Character.Encodable.Continuous.Class
        - Bio.Character.Encodable.Continuous.Internal
        - Bio.Character.Encodable.Dynamic
        - Bio.Character.Encodable.Dynamic.Class
        - Bio.Character.Encodable.Dynamic.Internal
        - Bio.Character.Encodable.Internal
        - Bio.Character.Encodable.Static
        - Bio.Character.Encodable.Static.Class
        - Bio.Character.Encodable.Static.Internal
        - Bio.Character.Encodable.Stream
        - Bio.Character.Exportable
        - Bio.Character.Exportable.Class
        - Bio.Graph.BinaryRenderingTree
        - Bio.Graph.Component
        - Bio.Graph.LeafSet
        - Bio.Graph.ReferenceDAG.Internal
        - Control.Evaluation.Internal
        - Control.Evaluation.Unit
        - Control.Monad.Logger
        - Data.Alphabet
        - Data.Alphabet.IUPAC
        - Data.Alphabet.Internal
        - Data.Alphabet.Special
        - Data.EdgeSet
        - Data.Range
        - Data.TCM
        - Data.TCM.Dense
        - Data.TCM.Dense.FFI
        - Data.TCM.Internal
        - Data.TCM.Memoized
        - Data.TCM.Memoized.FFI
        - Data.Vector.Custom
        - Data.Vector.NonEmpty
        - Test.Custom.NucleotideSequence
        - Test.QuickCheck.Arbitrary.Instances
        - Text.Newick.Class
        - Text.XML
        - Text.XML.Class
        - Text.XML.Custom
  - section:
    - name: test:unit-tests
    - message:
      - name: Redundant build-depends entry
      - depends: phylocomgraph

