allow-newer: true

compiler: ghc-8.4.1

compiler-check: match-exact

extra-deps:
  - base-compat-0.10.1
  - pretty-tree-0.1.0.0
  - matrix-0.3.6.0
  - wl-pprint-text-1.1.1.1

flags: {}

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility
# We use this upstream commit until it is uploaded to hackage and stackage respectively.
  - location:  https://github.com/ivan-m/graphviz/archive/b7539aa.zip
    extra-dep: true

#resolver: lts-11.5
resolver: nightly-2018-04-18
