allow-newer: true

compiler: ghc-8.4.4

compiler-check: match-exact

extra-deps:
  - pretty-tree-0.1.0.0
  - compact-0.1.0.1
  - tasty-rerun-1.1.12
  - megaparsec-7.0.4
  - vector-0.12.0.2

flags: {}

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths 

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility

require-stack-version: ">=1.7.1"

resolver: lts-12.13
