#allow-newer: true

compiler: ghc-8.6.5

compiler-check: match-exact

extra-deps:
  - bytestring-0.10.8.2
  - cassava-0.5.2.0
  - clustering-0.4.1
  - perfect-vector-shuffle-0.1.1
  - pretty-tree-0.1.0.0
  - tasty-rerun-1.1.14

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

require-stack-version: ">=2.1.3"

resolver: lts-14.1

dump-logs: all

packages:
  - .
  - lib/pcg-alphabet
  - lib/pcg-core
  - lib/pcg-data-normalization
  - lib/pcg-data-unification
  - lib/pcg-evaluation
  - lib/pcg-exportable
  - lib/pcg-file-parsers
  - lib/pcg-file-source
  - lib/pcg-language
  - lib/pcg-serialize
  - lib/pcg-tcm-memo
  - lib/pcg-utility
  - lib/pcg-validation-transformer