#allow-newer: true

compiler: ghc-8.6.5

compiler-check: match-exact

extra-deps:
  - bv-little-1.0.0
  - compact-0.1.0.1
  - graphviz-2999.20.0.3
  - pretty-tree-0.1.0.0
  - tasty-rerun-1.1.14
  - text-show-3.7.5
  - text-show-instances-3.7
  - mono-traversable-keys-0.1.0

#ghc-options:
#  "$everything": -j -fdiagnostics-color=always -fspecialize-aggressively -fexpose-all-unfoldings
#  "$locals": -fhide-source-paths 

local-bin-path: bin

require-stack-version: ">=1.9.1"

resolver: lts-13.20

dump-logs: all

packages:
  - .
  - lib/pcg-alphabet
  - lib/pcg-core
  - lib/pcg-data-normalization
  - lib/pcg-data-unification
  - lib/pcg-evaluation
  - lib/pcg-exportable
  - lib/pcg-file-parsers
  - lib/pcg-file-source
  - lib/pcg-language
  - lib/pcg-serialize
  - lib/pcg-tcm-memo
  - lib/pcg-utility
  - lib/pcg-validation-transformer