allow-newer: true

compiler: ghc-8.2.2
#compiler: ghc-8.2.

compiler-check: match-exact

extra-deps:
  - pretty-tree-0.1.0.0

flags: {}

ghc-options:
  "*": -j -fdiagnostics-color=always

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility
# We use this upstream commit until it is uploaded to hackage and stackage respectively.
  - location:  https://github.com/ivan-m/graphviz/archive/a099a07.zip
    extra-dep: true

resolver: nightly-2017-09-29

system-ghc: false


setup-info:

  ghc:
    linux64:
      8.2.2:
        url: https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-deb8-linux.tar.xz
#        url: https://downloads.haskell.org/~ghc/8.2.2-rc3/ghc-8.2.1.20171108-x86_64-deb8-linux.tar.xz
#        content-length: 127074124
#        sha1: 1bf4bf40f18dc62965d6a61f38a80f27b2aec0ec
    macosx:
      8.2.2:
        url: https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-apple-darwin.tar.xz
#        url: https://downloads.haskell.org/~ghc/8.2.2-rc3/ghc-8.2.1.20171108-x86_64-apple-darwin.tar.xz
#        content-length: 114066524
#        sha1: d99127a42b07efb57c381865395caeb457360733
    windows64:
      8.2.2:
        url: https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-unknown-mingw32.tar.xz
#        url: https://downloads.haskell.org/~ghc/8.2.2-rc3/ghc-8.2.1.20171108-x86_64-unknown-mingw32.tar.xz
#        content-length: 175160992
#        sha1: 3696c1077ff0d2832f0e594381c7679e2bf3babe
