allow-newer: true

compiler: ghc-8.8.1

compiler-check: match-exact

dump-logs: all

extra-deps:
  - algebraic-graphs-0.4
  - bv-little-1.1.1
  - clustering-0.4.1
  - compact-0.1.0.1
  - graphviz-2999.20.0.3
  - lens-4.18.1
  - microlens-0.4.11.2
  - perfect-vector-shuffle-0.1.1
  - mmark-0.0.7.2
  - megaparsec-8.0.0
  - pretty-tree-0.1.0.0
  - tasty-rerun-1.1.14
  - vector-th-unbox-0.2.1.7
  - wl-pprint-text-1.2.0.0

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - .

require-stack-version: ">=2.1.3"

resolver: nightly-2019-12-17
