allow-newer: true

compiler: ghc-8.8.0.20190721

compiler-check: match-exact

dump-logs: all

extra-deps:
  - bv-little-1.1.0
  - clustering-0.4.1
  - compact-0.1.0.1
  - graphviz-2999.20.0.3
  - matrices-0.5.0
  - mono-traversable-keys-0.1.0
  - perfect-vector-shuffle-0.1.0
  - pretty-tree-0.1.0.0
  - tasty-rerun-1.1.14
  - text-short-0.1.3
  - text-show-3.8.2
  - text-show-instances-3.8.1
  - validation-1.1
  - git: https://github.com/bgamari/attoparsec
    commit: e64bbfb34733f53236e6b05d2248a5896b46daf1
  - git: https://github.com/haskell/cabal
    commit: 27221efc89e25069f3ded141310aa0e63df9d8f5
    subdirs:
    - Cabal
  - git: https://github.com/haskell-vanguard/cabal-doctest
    commit: 98d7890b410968ff338ff661949304df75cdc169
  - git: https://github.com/GaloisInc/cereal
    commit: 3396176a36284d7aa53ffcb34a905a91a576832c
  - git: https://github.com/spl/dlist
    commit: 66dd57cc124df917f8cb1ae6eb1e6092ec18eea2
  - git: https://github.com/ekmett/lens
    commit: 87287dd248eb7e43fc7bf34ea0084b537a2b2fb4
  - git: https://github.com/monadfix/microlens
    commit: 0033b78a005bef20e37d033d2b34809ebe6f9e1b
    subdirs:
    - microlens
  - git: https://github.com/pcapriotti/optparse-applicative
    commit: 114e6ecaf390120508bca0f99c6f4fd4f5d0b233
  - git: https://github.com/haskell/parsec
    commit: 60dfb0cb6a711f141e5d8728af37de894e33795e
  - git: https://github.com/Gabriel439/Haskell-Pipes-Library
    commit: 37e4b33b24c4b0dfb26d424bced00af6f4c11333
  - git: https://github.com/haskell/primitive
    commit: 47c4341f4e0f6fbbc3c53f23ca71e588c9515e6d
  - git: https://github.com/nick8325/quickcheck
    commit: af14a56beda3bb02239ffb0ef7f8e9b393fec8e4
  - git: https://github.com/phadej/qc-instances
    commit: d39d60ed0a9673073d2a8e67947a7c7d99ffb41f
  - git: https://github.com/glguy/th-abstraction
    commit: 00fcd437f35c3049ccca70ff644bdf38e8dce8d0
  - git: https://github.com/haskell-vanguard/vector-th-unbox
    commit: 2fa686c70d4f10993ca7c73b510e18568620b1d0
  - git: https://github.com/haskell-vanguard/yaml
    commit: ef48de2ff3a551fdc6d3884fbe5755501abbad65
    subdirs:
    - yaml

#ghc-options:
#  "$everything": -j -fdiagnostics-color=always -fspecialize-aggressively -fexpose-all-unfoldings
#  "$locals": -fhide-source-paths 

local-bin-path: bin

packages:
  - .
  - lib/pcg-alphabet
  - lib/pcg-core
  - lib/pcg-data-normalization
  - lib/pcg-data-unification
  - lib/pcg-evaluation
  - lib/pcg-exportable
  - lib/pcg-file-parsers
  - lib/pcg-file-source
  - lib/pcg-language
  - lib/pcg-serialize
  - lib/pcg-tcm-memo
  - lib/pcg-utility
  - lib/pcg-validation-transformer

require-stack-version: ">=2.1.1"

resolver: nightly-2019-08-03

setup-info:
  ghc:
    linux32:
        8.8.0.20190721:
            url: "https://downloads.haskell.org/ghc/8.8.1-rc1/ghc-8.8.0.20190721-i386-deb9-linux.tar.xz"
            content-length: 204519496
            sha1: cc7de4ab0c963529487e6387dee8de87fe2d8b6e
    macosx:
        8.8.0.20190721:
            url: "https://downloads.haskell.org/ghc/8.8.1-rc1/ghc-8.8.0.20190721-x86_64-apple-darwin.tar.xz"
            content-length: 188586644
            sha1: d33ab464198b41f54596e297e16bb676d9700991
    linux64:
        8.8.0.20190721:
            url: "https://downloads.haskell.org/ghc/8.8.1-rc1/ghc-8.8.0.20190721-x86_64-deb9-linux.tar.xz"
            content-length: 200333084
            sha1: 56c1abc26372d4b202835c45c10d47afca7634a7
    windows64:
        8.8.0.20190721:
            url: "https://downloads.haskell.org/ghc/8.8.1-rc1/ghc-8.8.0.20190721-x86_64-unknown-mingw32.tar.xz"
            content-length: 224732484
            sha1: 7ab9486b3346de9cf48818806b6b85c7db9504d6
