allow-newer: true

compiler: ghc-8.6.3

compiler-check: match-exact

extra-deps:
#- Cabal-2.4.0.1
- compact-0.1.0.1
- graphviz-2999.20.0.2@sha256:5fad513f27c6fa4ee92f27461bb7386a5541b6b7edd601483fe693d4ac3963c5
#- polyparse-1.12.1
- pretty-tree-0.1.0.0
#- stm-2.5.0.0
- tasty-rerun-1.1.12

flags: {}

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility
  #We use this upstream commit until it is uploaded to hackage and stackage respectively.
  - location:  https://github.com/recursion-ninja/fgl/archive/d6735ce.zip
    extra-dep: true

require-stack-version: ">=1.7.1"

resolver: lts-13.0
