allow-newer: true

compiler: ghc-8.4.1

compiler-check: match-exact

extra-deps:
  - pretty-tree-0.1.0.0
  - base-compat-0.10.1
  - matrix-0.3.6.0

#  - MonadRandom-0.5.1
#  - random-shuffle-0.0.4
#  - wl-pprint-text-1.1.1.0

flags: {}

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility
# We use this upstream commit until it is uploaded to hackage and stackage respectively.
  - location:  https://github.com/ivan-m/graphviz/archive/a099a07.zip
    extra-dep: true

resolver: lts-11.4
