allow-newer: true

compiler: ghc-8.8.1

compiler-check: match-exact

dump-logs: all

extra-deps:
  - attoparsec-0.13.2.3
  - optparse-applicative-0.15.0.0
  - Cabal-3.0.0.0
  - clustering-0.4.1
  - lens-4.18
  - microlens-0.4.11.2
  - perfect-vector-shuffle-0.1.1
  - pretty-tree-0.1.0.0
  - polyparse-1.13
  - primitive-0.7.0.0
  - tasty-rerun-1.1.14
  - text-show-instances-3.8.1
  - validation-1.1
  - git: https://github.com/haskell-vanguard/vector-th-unbox
    commit: 2fa686c70d4f10993ca7c73b510e18568620b1d0

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - .
  - lib/pcg-alphabet
  - lib/pcg-core
  - lib/pcg-data-normalization
  - lib/pcg-data-unification
  - lib/pcg-evaluation
  - lib/pcg-exportable
  - lib/pcg-file-parsers
  - lib/pcg-file-source
  - lib/pcg-language
  - lib/pcg-serialize
  - lib/pcg-tcm-memo
  - lib/pcg-utility
  - lib/pcg-validation-transformer

require-stack-version: ">=2.1.3"

resolver: nightly-2019-09-11
