allow-newer: true

compiler: ghc-8.6.1

compiler-check: match-exact

extra-deps:
- pretty-tree-0.1.0.0
- tasty-rerun-1.1.12
- compact-0.1.0.1

flags: {}

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility
  #We use this upstream commit until it is uploaded to hackage and stackage respectively.
  - location:  https://github.com/recursion-ninja/fgl/archive/d6735ce.zip
    extra-dep: true

#resolver: lts-12.6
#resolver: lts-11.11
resolver: nightly-2018-09-28
#resolver: ghc-8.6.0.20180810


require-stack-version: ">=1.7.1"

resolver: lts-12.13

