allow-newer: true

compiler: ghc-8.6.3

compiler-check: match-exact

extra-deps:
  - compact-0.1.0.1
  - graphviz-2999.20.0.2@sha256:5fad513f27c6fa4ee92f27461bb7386a5541b6b7edd601483fe693d4ac3963c5
  - pretty-tree-0.1.0.0
  - tasty-rerun-1.1.12

flags: {}

ghc-options:
  "$everything": -j -fdiagnostics-color=always -fspecialize-aggressively -fexpose-all-unfoldings
  "$locals": -fhide-source-paths 

local-bin-path: bin

require-stack-version: ">=1.7.1"

resolver: lts-13.2
