allow-newer: true

compiler: ghc-8.4.0.20180118

compiler-check: match-exact

extra-deps:
  - pretty-tree-0.1.0.0

flags: {}

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility
# We use this upstream commit until it is uploaded to hackage and stackage respectively.
  - location:  https://github.com/ivan-m/graphviz/archive/a099a07.zip
    extra-dep: true

  - location:  https://github.com/haskell/primitive/archive/53f72ce.zip
    extra-dep: true

  - location:  https://github.com/ekmett/reflection/archive/eaa190c.zip
    extra-dep: true

resolver: lts-10.0
#resolver: nightly-2017-11-23

system-ghc: false

setup-info:
  ghc:
    linux64:
      8.4.0.20180118:
        url: https://downloads.haskell.org/~ghc/8.4.1-alpha2/ghc-8.4.0.20180118-x86_64-deb8-linux.tar.xz
    macosx:
      8.4.0.20180118:
        url: https://downloads.haskell.org/~ghc/8.4.1-alpha2/ghc-8.4.0.20180118-x86_64-apple-darwin.tar.xz
    windows64:
      8.4.0.20180118:
        url: https://downloads.haskell.org/~ghc/8.4.1-alpha2/ghc-8.4.0.20180118-x86_64-apple-darwin.tar.xz

