allow-newer: true

compiler: ghc-8.4.1

compiler-check: match-exact

extra-deps:
  - pretty-tree-0.1.0.0

  - hashtables-1.2.2.1
  - matrix-0.3.6.0
  - MonadRandom-0.5.1
  - random-shuffle-0.0.4
  - wl-pprint-text-1.1.1.0

#  - Glob-0.9.2
#  - QuickCheck-2.11.3
#  - bimap-0.3.3
#  - blaze-html-0.9.0.1
#  - case-insensitive-1.2.0.10
#  - colour-2.3.4
#  - dlist-0.8.0.4
#  - either-5
#  - fgl-5.5.4.0
#  - free-5
#  - hashable-1.2.6.1
#  - hashtables-1.2.2.1
#  - keys-3.12
#  - lens-4.16
#  - matrix-0.3.5.0
#  - megaparsec-6.4.0
#  - mono-traversable-1.0.8.1
#  - parallel-3.2.1.1
#  - parser-combinators-0.4.0
#  - pointed-5.0.1
#  - polyparse-1.12
#  - primitive-0.6.3.0
#  - random-shuffle-0.0.4
#  - safe-0.3.16
#  - scientific-0.3.5.2
#  - semigroupoids-5.2.2
#  - semigroups-0.18.4
#  - smallcheck-1.1.3.1
#  - split-0.2.3.3
#  - tasty-1.0.1
#  - tasty-hunit-0.10.0.1
#  - tasty-quickcheck-0.10
#  - tasty-smallcheck-0.8.1
#  - temporary-1.2.1.1
#  - unordered-containers-0.2.9.0
#  - vector-0.12.0.1
#  - vector-instances-3.4
#  - wl-pprint-text-1.1.1.0
#  - xml-1.3.14
#  - MonadRandom-0.5.1
#  - ansi-terminal-0.8.0.1
#  - async-2.2.1
#  - base-compat-0.9.3
#  - base-orphans-0.6
#  - bifunctors-5.5.2
#  - blaze-markup-0.8.2.0
#  - cabal-doctest-1.0.6
#  - call-stack-0.1.0
#  - clock-0.7.2
#  - comonad-5.0.3
#  - contravariant-1.4.1
#  - data-default-class-0.1.2.0
#  - distributive-0.5.3
#  - exceptions-0.9.0
#  - integer-logarithms-1.0.2
#  - kan-extensions-5.1
#  - logict-0.6.0.2
#  - loop-0.3.0
#  - optparse-applicative-0.14.2.0
#  - profunctors-5.2.2
#  - random-1.1
#  - reflection-2.1.3
#  - tagged-0.8.5
#  - tf-random-0.5
#  - th-abstraction-0.2.6.0
#  - transformers-base-0.4.4
#  - transformers-compat-0.6.0.6
#  - unbounded-delays-0.1.1.0
#  - vector-algorithms-0.7.0.1
#  - void-0.7.2
#  - StateVar-1.1.0.4
#  - adjunctions-4.4
#  - ansi-wl-pprint-0.6.8.2
#  - fail-4.9.0.0
#  - boxes-1.5.0
#  - blaze-builder-0.4.1

flags: {}

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility
# We use this upstream commit until it is uploaded to hackage and stackage respectively.
  - location:  https://github.com/ivan-m/graphviz/archive/a099a07.zip
    extra-dep: true
#  - location:  https://github.com/haskell/primitive/archive/53f72ce.zip
#    extra-dep: true

#  - location:  https://github.com/ekmett/reflection/archive/eaa190c.zip
#    extra-dep: true

resolver: lts-11.1
