allow-newer: true

compiler: ghc-8.2.2

compiler-check: match-exact

extra-deps:
  - pretty-tree-0.1.0.0

flags: {}

ghc-options:
  "*": -j -fdiagnostics-color=always

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-file-parsers
  - lib/pcg-language
  - lib/pcg-utility
  - lib/tcm-memo
# We use this upstream commit until it is uploaded to hackage and stackage respectively.
  - location:  https://github.com/ivan-m/graphviz/archive/a099a07.zip
    extra-dep: true

resolver: lts-10.0
#resolver: nightly-2017-11-23

system-ghc: false
