allow-newer: true

compiler: ghc-8.8.3

compiler-check: match-exact

dump-logs: all

extra-deps:
  - clustering-0.4.1
  - compact-0.1.0.1
  - pretty-tree-0.1.0.0

ghc-options:
  "$everything": -j -fdiagnostics-color=always
  "$locals": -fhide-source-paths

local-bin-path: bin

packages:
  - .

require-stack-version: ">=2.3.1"

resolver: lts-15.10
