allow-newer: true

compiler: ghc-8.8.0.20190613

compiler-check: match-exact

dump-logs: all

extra-deps:
  - bv-little-1.0.1
  - clustering-0.4.1
  - compact-0.1.0.1
  - graphviz-2999.20.0.3
  - matrices-0.5.0
  - mono-traversable-keys-0.1.0
  - perfect-vector-shuffle-0.1.0
  - pretty-tree-0.1.0.0
  - tasty-rerun-1.1.14
  - text-show-3.7.5
  - text-show-instances-3.7
  - validation-1.1
  - git: https://github.com/haskell/cabal
    commit: 27221efc89e25069f3ded141310aa0e63df9d8f5
    subdirs:
    - Cabal
  - git: https://github.com/phadej/cabal-doctest
    commit: 0db20e302caf205ce1e0ab960df8e0b63b7921f3
  - git: https://github.com/GaloisInc/cereal
    commit: 3396176a36284d7aa53ffcb34a905a91a576832c
  - git: https://github.com/spl/dlist
    commit: 66dd57cc124df917f8cb1ae6eb1e6092ec18eea2
  - git: https://github.com/monadfix/microlens
    commit: 0033b78a005bef20e37d033d2b34809ebe6f9e1b
    subdirs:
    - microlens
  - git: https://github.com/pcapriotti/optparse-applicative
    commit: 114e6ecaf390120508bca0f99c6f4fd4f5d0b233
  - git: https://github.com/Gabriel439/Haskell-Pipes-Library
    commit: 37e4b33b24c4b0dfb26d424bced00af6f4c11333
  - git: https://github.com/haskell/primitive
    commit: 47c4341f4e0f6fbbc3c53f23ca71e588c9515e6d
  - git: https://github.com/nick8325/quickcheck
    commit: af14a56beda3bb02239ffb0ef7f8e9b393fec8e4
  - git: https://github.com/phadej/qc-instances
    commit: d39d60ed0a9673073d2a8e67947a7c7d99ffb41f
  - git: https://github.com/glguy/th-abstraction
    commit: 00fcd437f35c3049ccca70ff644bdf38e8dce8d0

#ghc-options:
#  "$everything": -j -fdiagnostics-color=always -fspecialize-aggressively -fexpose-all-unfoldings
#  "$locals": -fhide-source-paths 

local-bin-path: bin

packages:
  - .
  - lib/pcg-alphabet
  - lib/pcg-core
  - lib/pcg-data-normalization
  - lib/pcg-data-unification
  - lib/pcg-evaluation
  - lib/pcg-exportable
  - lib/pcg-file-parsers
  - lib/pcg-file-source
  - lib/pcg-language
  - lib/pcg-serialize
  - lib/pcg-tcm-memo
  - lib/pcg-utility
  - lib/pcg-validation-transformer

require-stack-version: ">=2.1.1"

resolver: nightly-2019-07-19

setup-info:
  ghc:
    linux32:
        8.8.0.20190613:
            url: "https://downloads.haskell.org/~ghc/8.8.1-alpha2/ghc-8.8.0.20190613-i386-deb9-linux.tar.xz"
            content-length: 204060792
            sha1: 0fe7fc95073602078e0677ae623dd02f46ae3a5b
    macosx:
        8.8.0.20190613:
            url: "https://downloads.haskell.org/~ghc/8.8.1-alpha2/ghc-8.8.0.20190613-x86_64-apple-darwin.tar.xz"
            content-length: 184846152
            sha1: 116bdaadcde045f78adcf1ffce291c79fb1c3eb6
    linux64:
        8.8.0.20190613:
            url: "https://downloads.haskell.org/~ghc/8.8.1-alpha2/ghc-8.8.0.20190613-x86_64-deb9-linux.tar.xz"
            content-length: 199898532
            sha1: 11360a17f61da02c82d0f64f07e124479cedecc4
    linux64-tinfo6:
        8.8.0.20190613:
            url: "https://downloads.haskell.org/~ghc/8.8.1-alpha2/ghc-8.8.0.20190613-x86_64-fedora27-linux.tar.xz"
            content-length: 201560804
            sha1: 07eb8ab473f2aa3c21ac2b497142a01466ace5ee
    windows64:
        8.8.0.20190613:
            url: "https://downloads.haskell.org/~ghc/8.8.1-alpha2/ghc-8.8.0.20190613-x86_64-unknown-mingw32.tar.xz"
            content-length: 224468920
            sha1: b4a3b2b45625eb32dd7f892246da9a602d9ce7db

