allow-newer: true

compiler: ghc-8.2.0.20170507

compiler-check: match-exact

flags: {}

extra-deps:
  - containers-0.5.8.1
  - pretty-tree-0.1.0.0
  - quickcheck-properties-0.1

ghc-options:
  "*": -j

local-bin-path: bin

packages:
 - '.'
 - location:  https://github.com/haskell/deepseq/archive/0b22c98.zip
   extra-dep: true
 - location:  https://github.com/haskell/deepseq/archive/0b22c98.zip
   extra-dep: true
 - location:  https://github.com/ekmett/distributive/archive/3f29260.zip
   extra-dep: true
 - location:  https://github.com/ekmett/lens/archive/7031e00.zip
   extra-dep: true
 - location:  https://github.com/ekmett/semigroupoids/archive/c3297f9.zip
   extra-dep: true

resolver: lts-8.19

