allow-newer: true

compiler: ghc-8.2.1

compiler-check: match-exact

extra-deps:
  - megaparsec-6.0.2
  - pretty-tree-0.1.0.0
  - quickcheck-properties-0.1

flags: {}

ghc-options:
  "*": -j

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-language

resolver: nightly-2017-07-31

system-ghc: false

