allow-newer: true

compiler: ghc-8.0.2

compiler-check: match-exact

flags: {}

extra-deps:
  - containers-0.5.8.1
  - megaparsec-6.0.0
  - parser-combinators-0.1
  - pretty-tree-0.1.0.0
  - quickcheck-properties-0.1

ghc-options:
  "*": -j

local-bin-path: bin

packages:
  - '.'
  - lib/pcg-language
  - location: https://github.com/mrkkrp/megaparsec/archive/ed9a823.zip
    extra-dep: true
  - location: https://github.com/mrkkrp/parser-combinators/archive/master.zip
    extra-dep: true
    
resolver: lts-8.20

