flags: {}

setup-info:
  ghc:
    windows64:
      8.0.2:
        url: https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-x86_64-unknown-mingw32.tar.xz
        sha1: a536228cb7265aef19b2842a2c81cfe9ca372e45
        content-length: 97162136
    linux64:
      8.0.2:
        url: https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-x86_64-deb8-linux.tar.xz
        sha1: f298b7d0f37cc9ded7ac66b2662b0fa5ac6d0809
        content-length: 114373576
    macosx:
      8.0.2:
        url: https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-x86_64-apple-darwin.tar.xz
        sha1: d87048467786a7b9667aef0a78d7ffd8779425b2
        content-length: 113945284

extra-deps:
- bv-0.4.1
- containers-0.5.8.1
- lens-4.15.1
- vector-instances-3.4

compiler-check: match-exact
compiler: ghc-8.0.2

resolver: lts-7.14
