allow-newer: true

compiler: ghc-8.0.2

compiler-check: match-exact

flags: {}

extra-deps:
  - containers-0.5.8.1
  - pretty-tree-0.1.0.0
  - quickcheck-properties-0.1

ghc-options:
  "*": -j

local-bin-path: bin

packages:
  - '.'

resolver: lts-8.15

