flags: {}
extra-package-dbs: []
local-bin-path: bin
packages:
- '.'
system-ghc: false
extra-deps:
- Glob-0.7.11
- MonadRandom-0.4.2.3
- QuickCheck-2.9.1
- StateVar-1.1.0.4
- abstract-deque-0.3
- abstract-par-0.3.3
- adjunctions-4.3
- aeson-0.11.2.1
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- attoparsec-0.13.0.2
- base-orphans-0.5.4
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- bv-0.4.1
- cassava-0.4.5.0
- cereal-0.5.3.0
- clock-0.7.2
- comonad-5
- contravariant-1.4
- criterion-1.1.1.0
- data-default-class-0.1.2.0
- distributive-0.5.0.2
- dlist-0.8.0.1
- either-4.4.1.1
- erf-2.0.0.0
- exceptions-0.8.3
- fail-4.9.0.0
- free-4.12.4
- hashable-1.2.4.0
- hastache-0.6.1
- ieee754-0.7.8
- kan-extensions-5.0.1
- keys-3.11
- logict-0.6.0.2
- loop-0.3.0
- math-functions-0.2.0.1
- matrix-0.3.5.0
- megaparsec-5.0.0
- mmorph-1.0.6
- monad-control-1.0.1.0
- monad-par-0.3.4.8
- monad-par-extras-0.3.3
- mono-traversable-1.0.0.1
- mtl-2.2.1
- mwc-random-0.13.4.0
- optparse-applicative-0.12.1.0
- parallel-3.2.1.0
- parsec-3.1.11
- pointed-5
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- quickcheck-properties-0.1
- random-1.1
- regex-base-0.93.2
- regex-tdfa-1.2.2
- safe-0.3.9
- scientific-0.3.4.9
- semigroupoids-5.1
- semigroups-0.18.2
- smallcheck-1.1.1
- split-0.2.3.1
- statistics-0.13.3.0
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.5
- tasty-0.11.0.4
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- tasty-smallcheck-0.8.1
- text-1.2.2.1
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.2
- vector-instances-3.3.1
- vector-th-unbox-0.2.1.6
- void-0.7.1
resolver: ghc-8.0.1
