extra-deps:
- accelerate-2.0.0.0
- cuda-0.7.0.0
- exception-mtl-0.4
- language-c-quote-0.11.4.1
- mainland-pretty-0.4.1.2
- Safe-0.1
- unique-0

extra-package-dbs: []

flags: {}

packages:
- '.'
- location: https://github.com/AccelerateHS/accelerate-cuda/archive/master.zip
- location: https://github.com/AccelerateHS/accelerate/archive/master.zip

resolver: lts-6.1

system-ghc: false